import type { Metadata } from "next";
import { Inter, Ubuntu, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import NavLinks from "./NavLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className bg-sky-200`}>
        <header className="bg-sky-700 flex justify-between h-44 laptop:flex-col laptop:items-center laptop:h-52">
          <Header />
          <nav className="h-full ">
            <NavLinks />
          </nav>
        </header>
        <main className="min-h-svh">{children}</main>
      </body>
    </html>
  );
}
