import type { Metadata } from "next";
import { Inter, Ubuntu, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/ui/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className bg-sky-200 h-svh m-0 `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
