import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Header from "@/app/components/header/Header";
import NavLinks from "@/app/components/header/NavLinks";
import { UserProvider } from "./lib/contexts/UserContext";
import { ubuntu } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`ubuntu.className bg-sky-200`}>
        <UserProvider>
          <header className="bg-sky-700 flex justify-between h-56 laptop:flex-col laptop:items-center laptop:h-56 laptop:w-screen">
            <Header />
            <nav className="h-full w-full text-center flex justify-center">
              <NavLinks />
            </nav>
          </header>
          <main className="min-h-svh">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
